import { ProductType } from "@repo/types";

// Extended mock data for search functionality
export const extendedMockProducts = [
  {
    ProductID: "product-1",
    ProductSizeID: ["size-1", "size-2", "size-3", "size-4"],
    Type: ProductType.Shirt,
    Description: "Áo thun chất liệu cotton cao cấp, thoáng mát và bền đẹp. Thiết kế đơn giản, dễ phối đồ.",
    Name: "Áo thun Basic",
    Status: "ACTIVE" as const,
    Images: ["https://placehold.co/300x300/ffffff/000000?text=Áo+thun+Basic"],
    CurrentPrice: 150000,
    OriginalPrice: 180000,
    Discount: 17,
    Rating: 4.5,
    ReviewCount: 128,
    IsTrending: false,
    Promotion: "SALE",
  },
  {
    ProductID: "product-2",
    ProductSizeID: ["size-5"],
    Type: ProductType.Sticker,
    Description: "Sticker vinyl chất lượng cao, bền màu và dính chắc. Phù hợp để trang trí laptop, điện thoại, sổ tay.",
    Name: "Sticker Meme Collection",
    Status: "ACTIVE" as const,
    Images: ["https://placehold.co/300x300/ff69b4/ffffff?text=Sticker+Meme"],
    CurrentPrice: 25000,
    OriginalPrice: 35000,
    Discount: 29,
    Rating: 4.6,
    ReviewCount: 89,
    IsTrending: true,
    Promotion: "HOT",
  },
  {
    ProductID: "product-3",
    ProductSizeID: ["size-6"],
    Type: ProductType.Keyring,
    Description: "Móc khóa kim loại mạ vàng, thiết kế độc đáo. Làm quà tặng ý nghĩa hoặc trang trí túi xách.",
    Name: "Móc khóa Metal Art",
    Status: "ACTIVE" as const,
    Images: ["https://placehold.co/300x300/ffd700/000000?text=Móc+khóa+Metal"],
    CurrentPrice: 45000,
    OriginalPrice: 60000,
    Discount: 25,
    Rating: 4.8,
    ReviewCount: 156,
    IsTrending: false,
    Promotion: "LIMITED",
  },
  {
    ProductID: "product-4",
    ProductSizeID: ["size-1", "size-2"],
    Type: ProductType.Shirt,
    Description: "Áo hoodie ấm áp cho mùa đông, chất liệu fleece mềm mại. Có túi kangaroo tiện lợi.",
    Name: "Hoodie Winter",
    Status: "ACTIVE" as const,
    Images: ["https://placehold.co/300x300/4169e1/ffffff?text=Hoodie+Winter"],
    CurrentPrice: 280000,
    OriginalPrice: 350000,
    Discount: 20,
    Rating: 4.7,
    ReviewCount: 203,
    IsTrending: true,
    Promotion: "NEW",
  },
  {
    ProductID: "product-6",
    ProductSizeID: ["size-1", "size-2", "size-3"],
    Type: ProductType.Shirt,
    Description: "Áo thun vintage với thiết kế retro, chất liệu cotton 100% mềm mại.",
    Name: "Áo thun Vintage Retro",
    Status: "ACTIVE" as const,
    Images: ["https://placehold.co/300x300/8b4513/ffffff?text=Vintage+Retro"],
    CurrentPrice: 180000,
    OriginalPrice: 220000,
    Discount: 18,
    Rating: 4.8,
    ReviewCount: 156,
    IsTrending: true,
    Promotion: "HOT",
  },
  {
    ProductID: "product-7",
    ProductSizeID: ["size-5"],
    Type: ProductType.Sticker,
    Description: "Sticker gaming collection với các icon game nổi tiếng, chất lượng cao.",
    Name: "Sticker Gaming Collection",
    Status: "ACTIVE" as const,
    Images: ["https://placehold.co/300x300/00ff00/000000?text=Gaming+Stickers"],
    CurrentPrice: 25000,
    OriginalPrice: 35000,
    Discount: 29,
    Rating: 4.6,
    ReviewCount: 89,
    IsTrending: false,
    Promotion: "SALE",
  },
  {
    ProductID: "product-8",
    ProductSizeID: ["size-6"],
    Type: ProductType.Keyring,
    Description: "Móc khóa anime với thiết kế 3D, chất liệu PVC cao cấp.",
    Name: "Móc khóa Anime 3D",
    Status: "ACTIVE" as const,
    Images: ["https://placehold.co/300x300/ff69b4/ffffff?text=Anime+3D"],
    CurrentPrice: 65000,
    OriginalPrice: 85000,
    Discount: 24,
    Rating: 4.9,
    ReviewCount: 234,
    IsTrending: true,
    Promotion: "NEW",
  },
  {
    ProductID: "product-9",
    ProductSizeID: ["size-1", "size-2", "size-3", "size-4"],
    Type: ProductType.Shirt,
    Description: "Áo thun graphic với họa tiết độc đáo, phong cách streetwear hiện đại.",
    Name: "Áo thun Graphic Street",
    Status: "ACTIVE" as const,
    Images: ["https://placehold.co/300x300/000000/ffffff?text=Graphic+Street"],
    CurrentPrice: 200000,
    OriginalPrice: 250000,
    Discount: 20,
    Rating: 4.7,
    ReviewCount: 178,
    IsTrending: false,
    Promotion: "LIMITED",
  },
  {
    ProductID: "product-10",
    ProductSizeID: ["size-5"],
    Type: ProductType.Sticker,
    Description: "Sticker kawaii với các nhân vật đáng yêu, màu sắc tươi sáng.",
    Name: "Sticker Kawaii Set",
    Status: "ACTIVE" as const,
    Images: ["https://placehold.co/300x300/ffc0cb/000000?text=Kawaii+Set"],
    CurrentPrice: 30000,
    OriginalPrice: 40000,
    Discount: 25,
    Rating: 4.5,
    ReviewCount: 67,
    IsTrending: false,
    Promotion: "CUTE",
  },
  {
    ProductID: "product-11",
    ProductSizeID: ["size-1", "size-2", "size-3"],
    Type: ProductType.Shirt,
    Description: "Áo thun oversize phong cách Hàn Quốc, chất liệu cotton mềm mại.",
    Name: "Áo thun Oversize K-Style",
    Status: "ACTIVE" as const,
    Images: ["https://placehold.co/300x300/ff6b6b/ffffff?text=K-Style"],
    CurrentPrice: 220000,
    OriginalPrice: 280000,
    Discount: 21,
    Rating: 4.9,
    ReviewCount: 312,
    IsTrending: true,
    Promotion: "TRENDING",
  },
  {
    ProductID: "product-12",
    ProductSizeID: ["size-5"],
    Type: ProductType.Sticker,
    Description: "Sticker minimalist với thiết kế tối giản, phù hợp trang trí văn phòng.",
    Name: "Sticker Minimalist Pack",
    Status: "ACTIVE" as const,
    Images: ["https://placehold.co/300x300/2c3e50/ffffff?text=Minimalist"],
    CurrentPrice: 20000,
    OriginalPrice: 30000,
    Discount: 33,
    Rating: 4.4,
    ReviewCount: 45,
    IsTrending: false,
    Promotion: "OFFICE",
  },
];
